name: retro-mike-wojakcoin
services:
  app:
    container_name: wjk
    image: theretromike/nodes:wojak
    restart: always
    volumes:
      - /media/ZimaOS-HD/wjk:/root/.wojakcoin
    ports:
      - "7017:7017"
      - "9017:9017"
    command: "/usr/bin/wojakcoind -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7017 -rpcbind=0.0.0.0 -rpcport=9017 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Wojakcoin Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Wojakcoin Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://wojakcoin.cash/wojak-logo.png
  thumbnail: ""
  title:
    en_us: Wojakcoin (WJK) Node
  category: RetroMike
  port_map: "8888"
