name: wvk2017-silver
services:
  app:
    container_name: btcs
    image: wvk2017/nodes:bitcoinsilver
    restart: always
    volumes:
      - /media/ZimaOS-HD/btcs:/root/.bitcoinsilver
    ports:
      - "7015:7015"
      - "9015:9015"
    command: "/usr/bin/bitcoinsilverd -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7015 -rpcbind=0.0.0.0 -rpcport=9015 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword -addnode=89.163.242.248:10566 -addnode=95.141.241.26:10566"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Bitcoin Silver Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Bitcoin Silver Cryptocurrency Node.
  developer: Wvk2017
  author: Wvk2017
  icon: https://avatars.githubusercontent.com/u/185931597?s=200&v=4
  thumbnail: ""
  title:
    en_us: Bitcoin Silver (BTCS) Node
  category: Wvk2017
  port_map: "8888"
