name: wvk2017-litecoin-cash
services:
  app:
    container_name: lcc
    image: theretromike/nodes:litecoincash
    restart: always
    volumes:
      - /media/ZimaOS-HD/litecoincash:/root/.litecoincash
    ports:
      - "7018:7018"
      - "9018:9018"
    command: "/usr/bin/litecoincashd -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7018 -rpcbind=0.0.0.0 -rpcport=9018 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword -powalgo=sha256d -addnode=108.239.16.64 -addnode=108.249.26.52 -addnode=108.91.11.33 -addnode=109.58.29.116 -addnode=136.243.145.143 -addnode=137.101.181.79 -addnode=139.162.153.168 -addnode=151.46.23.73 -addnode=164.68.108.60 -addnode=173.72.23.158 -addnode=176.150.209.154 -addnode=185.54.177.114 -addnode=185.54.177.84"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Litecoin cash Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Litecoin cash Cryptocurrency Node.
  developer: Wvk2017
  author: Wvk2017
  icon: https://avatars.githubusercontent.com/u/185931597?s=200&v=4
  thumbnail: ""
  title:
    en_us: Litecoin cash (lcc) Node
  category: Wvk2017
  port_map: "8888"
