name: retro-mike-nitocoin
services:
  app:
    container_name: nito
    image: theretromike/nodes:nitocoin
    restart: always
    volumes:
      - /media/ZimaOS-HD/nito:/root/.nito
    ports:
      - "7020:7020"
      - "9020:9020"
    command: "/usr/bin/nitod -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7020 -rpcbind=0.0.0.0 -rpcport=9020 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Nitcoin (NITO) Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Nitcoin (NITO) Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://miningpoolstats.stream/ico/nitocoin.webp
  thumbnail: ""
  title:
    en_us: Nitcoin (NITO) Cryptocurrency Node
  category: RetroMike
  port_map: "8888"
