name: retro-mike-bitcoin-cash-ii
services:
  app:
    container_name: bch2
    image: theretromike/nodes:bitcoincashii
    restart: always
    volumes:
      - /media/ZimaOS-HD/bch2:/root/.bitcoincashII
    ports:
      - "7016:7016"
      - "9016:9016"
    command: "/usr/bin/bitcoincashIId -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7016 -rpcbind=0.0.0.0 -rpcport=9016 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Bitcoin Cash II Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Bitcoin Case II Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://bitcoin-ii.org/logo.png
  thumbnail: ""
  title:
    en_us: Bitcoin Cash II (BCH2) Node
  category: RetroMike
  port_map: "8888"
