name: wvk2017-miningcore-webui
services:
  app:
    container_name: miningcorewebui
    image: wvk2017/miningcorewebui:latest
    restart: always
    volumes:
      - /media/ZimaOS-HD/miningcore:/app/miningcore
    ports:
      - "81:8080"
    environment:
      - API_BASE_URL=http://192.168.1.100:4000/api
      - MININGCORE_HOST=192.168.1.101
      - PLATFORM=ZIMAOS
      - POOL_NAME=Self-Hosted Mining Pool
      - POSTGRES_DATABASE=zimaos
      - POSTGRES_HOST=192.168.1.100
      - POSTGRES_PASSWORD=P@ssw0rd
      - POSTGRES_USER=admin
      - PUID=1000
      - STRATUM_HOST=192.168.1.100
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Miningcore Web UI
  tagline:
    en_us: Miningcore Web UI
  developer: wvk2017
  author: wvk2017
  icon: https://raw.githubusercontent.com/TheRetroMike/retromike-umbrel-app-store/master/retro-mike-miningcore-webui/webui.png
  thumbnail: ""
  store_app_id: wvk2017-miningcore-webui
  title:
    en_us: Miningcore Web UI
  category: wvk2017
  port_map: "81"
