name: wvk2017-bch2
services:
  app:
    container_name: bch2
    image: wvk2017/nodes:bch2
    restart: always
    volumes:
      - /media/ZimaOS-HD/NodeData/bch2:/root/.bitcoincashII
    ports:
      - "7031:7031"
      - "9031:9031"
    command: "/usr/bin/bitcoincashIId -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7031 -rpcbind=0.0.0.0 -rpcport=9031 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword"
    x-casaos:
      volumes:
        - container: /root/.bitcoincashIId
          description:
            en_us: 'Container Path: /root/.bitcoincashII'
      ports:
        - container: "7031"
          description:
            en_us: 'Container Port: 7031'
        - container: "9031"
          description:
            en_us: 'Container Port: 9031'
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: bitcoincashII (BCH2) Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: bitcoincashII (bch2) Cryptocurrency Node.
  developer: wvk2017
  author: wvk2017
  icon: https://miningpoolstats.stream/ico/bitcoincash2.webp
  thumbnail: ""
  title:
    en_us: bitcoincashII (BCH2) Node
  category: WVK2017
  port_map: "8888"
