name: retro-mike-litecoincash-minotaurx
services:
  app:
    container_name: lcc_minotaurx
    image: theretromike/nodes:litecoincash
    restart: always
    volumes:
      - /media/ZimaOS-HD/lcc:/root/.litecoincash
    ports:
      - "7019:7019"
      - "9019:9019"
    command: "/usr/bin/litecoincashd -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7019 -rpcbind=0.0.0.0 -rpcport=9019 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword -powalgo=minotaurx -addnode=108.239.16.64 -addnode=108.249.26.52 -addnode=108.91.11.33 -addnode=109.58.29.116 -addnode=136.243.145.143 -addnode=137.101.181.79 -addnode=139.162.153.168 -addnode=151.46.23.73 -addnode=164.68.108.60 -addnode=173.72.23.158 -addnode=176.150.209.154 -addnode=185.54.177.114 -addnode=185.54.177.84"
x-casaos:
  architectures:
    - amd64
  main: app
  description:
    en_us: Litecoin Cash (MinotaurX) Cryptocurrency Node. Can be used in conjunction with Miningcore Apps to solo mine.
  tagline:
    en_us: Litecoin Cash (MinotaurX) Cryptocurrency Node.
  developer: Retro Mike
  author: Retro Mike
  icon: https://miningpoolstats.stream/ico/litecoincash.webp
  thumbnail: ""
  title:
    en_us: Litecoin Cash (MinotaurX) Cryptocurrency Node
  category: RetroMike
  port_map: "8888"
