version: "3.7"

services:
  fractald:
    image: ghcr.io/willitmod/fracattack-fractald:0.3.1-dev
    container_name: fracattack-app
    restart: unless-stopped
    stop_grace_period: 15m30s
    volumes:
      # ZimaOS AppData paden
      - /DATA/AppData/fracattack/data/node:/data
      - /DATA/AppData/fracattack/data/templates/fractald-entrypoint.sh:/fractald-entrypoint.sh:ro
      - /DATA/AppData/fracattack/data:/appdata
    ports:
      - "28343:28343/tcp" # Bitcoin P2P
      - "3080:3000"       # Web interface direct op poort 3080
    environment:
      RPC_USER: "fractal"
      RPC_PASSWORD: "MijnVeiligWachtwoordHier" # Pas aan naar wens
      BTC_P2P_PORT: "28343"
      BTC_RPC_PORT: "28342"
      BTC_ZMQ_HASHBLOCK_PORT: "28345"
      PAYOUT_ADDRESS: "bc1qp05vuzc5x4ym3cujh666xm6mzh0q6yqmkmtndl"
      JWT_SECRET: "EenWillekeurigeGeheimeTokenHier"
    entrypoint: ["/bin/sh", "/fractald-entrypoint.sh"]
